spring:
  redis:
    host: localhost
    password:
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: 1
  session:
    timout: 600
    store-type: redis
    redis:
      flush-mode: on-save